- hosts: cluster
  remote_user: "{{ remote_user }}"

  tasks:
  - name: unzip the spark to service directory
    action: unarchive src={{ source_dir }}/spark-{{ spark_version }}.tgz dest={{ service_dir }} copy=no

  - name: generate hive-site.xml for spark
    template: src=templates/hive-site.j2 dest={{ service_dir }}/spark-{{ spark_version }}/conf/hive-site.xml owner={{ remote_user }} mode=0644

  - name: generate spark-env.j2 for spark
    template: src=templates/spark-env.j2 dest={{ service_dir }}/spark-{{ spark_version }}/conf/spark-env.sh owner={{ remote_user }} mode=0644
