- hosts: data1
  remote_user: "{{ remote_user }}"

  tasks:
  - name: unzip the hive to service directory
    action: unarchive src={{ source_dir }}/apache-hive-{{ hive_version }}-bin.tar.gz dest={{ service_dir }} copy=no
    environment:
      HIVE_HOME: "{{ service_dir }}/hive-{{ hive_version }}"

  # - name: install the mysql package
  #   action: yum name=mysql-server.x86_64 state=present
  #
  # - name: install the mysql-python package
  #   action: yum name=MySQL-python.x86_64 state=present

  # - name: ensure mysql is running (and enable it at boot)
  #   service: name=mysqld state=started enabled=yes

  - name: create database for hive
    mysql_db: name=hive login_user=root login_password={{ mysql_root_pass }} state=present

  - name: create user for hive
    mysql_user: name=hive password=hive login_user=root login_password={{ mysql_root_pass }} priv=hive.*:w state=present

  - name: generate hive-site.xml for hive
    template: src=templates/hive-site.j2 dest={{ service_dir }}/apache-hive-{{ hive_version }}-bin/conf/hive-site.xml owner={{ remote_user }} mode=0644

  - name: put mysql driver into hive classpath
    action: copy src=./lib-files/mysql-connector-java-5.1.24.jar dest={{ service_dir }}/apache-hive-{{ hive_version }}-bin/lib/mysql-connector-java-5.1.24.jar owner={{ remote_user }} mode=0644
