- hosts: data1
  remote_user: {{ remote_user }}

  tasks:
  - name: mkdir for hive logs
    action: file path={{ data_dir }}/hive/log state=directory mode=0755

  - name: start the hive metastore service
    shell: nohup {{ service_dir }}/apache-hive-{{ hive_version }}-bin/bin/hive --service metastore > {{ data_dir }}/hive/log/metastore.log 2>&1 &
    environment:
      HADOOP_HOME: "{{ service_dir }}/hadoop-{{ hadoop_version }}"

  - name: start the spark-sql service
    action: command {{ service_dir }}/spark-{{ spark_version }}-bin-hadoop{{ spark_hadoop_version }}/sbin/start-thriftserver.sh
    environment:
      SPARK_LOG_DIR: "{{ data_dir }}/spark/log"
      SPARK_WORKER_DIR: "{{ data_dir }}/spark/work"
      SPARK_LOCAL_DIRS: "{{ data_dir }}/spark/data"
